services:
  app:
    container_name: nodeportfolio
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    volumes:
      - .:/app
      - /app/node_modules

networks:
  default:
    driver: bridge